sudo: required
services: 
  - docker

before_install:
  - docker build -t mayankpal/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mayankpal/docker-react npm run test -- --coverage
